import { Router } from "express";
import upload, { fileType } from "../../utils/multer.js";
import * as userController from './user.controller.js';
import validation from "../../midleware/validation.js";
import {asyncHandler} from "../../utils/asyncHandler.js";
import { LoginSchema, RegisterSchema } from "./user.validation.js";
const router = Router();
router.post('/Register',validation(RegisterSchema),asyncHandler(userController.Register));
router.post('/login',validation(LoginSchema),asyncHandler(userController.Login));
router.post('/uploadExcel',upload(fileType.excel).single('excel') ,asyncHandler(userController.addUserExcel));
router.post('/uploadImage',upload(fileType.image).single('image'),asyncHandler(userController.uploadImage));
export default router;